if(WIN32)
    set(CMAKE_FIND_ROOT_PATH /c/msys64/mingw64/bin)
    set(TOOLCHAIN_PREFIX x86_64-w64-mingw64)
endif()

set(CMAKE_C_COMPILER gcc${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_CXX_COMPILER g++${CMAKE_EXECUTABLE_SUFFIX})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)